const GET_NEXT_MONTH = 'GET_NEXT_MONTH';
const GET_PREV_MONTH = 'GET_PREV_MONTH';
const SET_DATE = 'SET_DATE';
const SET_OPTIONS = 'SET_OPTIONS';
const ADD_EVENT = 'ADD_EVENT';
const REMOVE_EVENT = 'REMOVE_EVENT';

export { GET_NEXT_MONTH, GET_PREV_MONTH, SET_DATE, ADD_EVENT, REMOVE_EVENT, SET_OPTIONS };
